app.py
from flask import Flask
from werkzeug import run_simple
from werkzeug.middleware.profiler import ProfilerMiddleware

from routes import adx_abctrainer_bp

app = Flask(__name__, instance_relative_config=True)
app.config.from_object('config')
app.config.from_pyfile('config.py')
app.register_blueprint(adx_abctrainer_bp)

if __name__ == '__main__':
    app.run()

routes.py
import random
from pathlib import Path

from flask import Blueprint, render_template, redirect, url_for, request, flash

from adx_abctrainer import parse_word, WORDS_RANDOM, WORDS_PRESELECTED, WORD_LENGTH_MIN, \
    WORD_LENGTH_MAX, INSTANCE_PATH
from form import InputForm, RandomForm, AddWordForm

adx_abctrainer_bp = Blueprint('adx_abctrainer', __name__, template_folder='templates/adx_abctrainer/')

# @adx_abctrainer_bp.route('/')
# def abctrainer_subdomain():
#     return redirect(url_for('.abctrainer_form'))

@adx_abctrainer_bp.route('/', methods=["GET", "POST"])
def abctrainer_form():
    form = InputForm()
    form_2 = RandomForm()
    submitted = {'word':form.data['submit_word'],'random':form_2.data['submit_random']}

    if form.validate_on_submit() and submitted['word']:
        return redirect(url_for('.abctrainer_word', word = form.word.data))
    elif form_2.validate_on_submit() and submitted['random']:
        return redirect(url_for('.abctrainer_random', min=form_2.min.data,max=form_2.max.data))
    elif form.validate_on_submit() and submitted['word'] or form_2.validate_on_submit() and submitted['random']:
        flash("You should not see this")

    return render_template("adx_abctrainer/form.html", form=form, form_2 = form_2, submitted = submitted, word_list = WORDS_PRESELECTED, min=WORD_LENGTH_MIN, max=WORD_LENGTH_MAX)

@adx_abctrainer_bp.route('/<word>', methods=["GET", "POST"])
def abctrainer_word(word):

    form_2 = RandomForm()
    min_length = int(request.args.get('min', WORD_LENGTH_MIN))
    max_length = int(request.args.get('max', WORD_LENGTH_MAX))

    if form_2.validate_on_submit():
        return redirect(url_for('.abctrainer_random', min=form_2.min.data,max=form_2.max.data))

    if word.isalpha() and len(word) >= WORD_LENGTH_MIN and len(word) <= WORD_LENGTH_MAX:
        word = parse_word(word)
        return render_template('adx_abctrainer/word.html', word=word, form_2 = form_2, randomize=False, min=min_length, max=max_length, min_abs=WORD_LENGTH_MIN, max_abs = WORD_LENGTH_MAX)
    else:
        flash(f"Something went wrong:{word.isalpha()},{len(word) >= WORD_LENGTH_MIN}, {len(word) <= WORD_LENGTH_MAX}")

@adx_abctrainer_bp.route('/random')
def abctrainer_random():
    min_length = int(request.args.get('min',WORD_LENGTH_MIN))
    max_length = int(request.args.get('max',WORD_LENGTH_MAX))

    possible_words = [word for word in WORDS_RANDOM if len(word) >= min_length and len(word) <= max_length]
    if len(possible_words) > 0:
        word = random.choice(possible_words)
    else: # fallback in case no word of the selected length is in the list
        word = max(WORDS_RANDOM, key=len)

    if word != '':
        return redirect(url_for('.abctrainer_word', word = word, min=min_length, max=max_length))
    return redirect('/')

@adx_abctrainer_bp.route('/neues_wort', methods=["GET", "POST"])
def abctrainer_new():
    form = AddWordForm()

    if form.validate_on_submit():
        new_word = form.word.data
        flash(f'Verarbeite {new_word}')

        # add new word or delete if already contained in lists
        WORDS_PRESELECTED.append(new_word) if not new_word in WORDS_PRESELECTED else WORDS_PRESELECTED.remove(new_word)
        WORDS_RANDOM.append(new_word) if not new_word in WORDS_RANDOM else WORDS_RANDOM.remove(new_word)

        flash(f'Liste: {WORDS_PRESELECTED}')

        # overwrite txt with pre-selected files according to new list
        with open(Path(f'{INSTANCE_PATH}/woerter_vorauswahl.txt'), 'w') as f:
            for word in WORDS_PRESELECTED:
                f.write(f'{word}\n')

        #return redirect(url_for('.adx_abctrainer_new'))

    return render_template("adx_abctrainer/form.html", form=form, form_2=None, word_list=WORDS_PRESELECTED, min=WORD_LENGTH_MIN, max=WORD_LENGTH_MAX)

templates/adx_abctrainer/form.html
{% extends "base.html" %}
{% block title %}
    AUDAX - ABC Trainings Generator
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='abc_trainer.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="adx-logo-row adx-row row">
            <div class="col-4"><a href="{{ url_for('adx_abctrainer.abctrainer_form') }}"><img width="160px" src="{{ url_for('static',filename='img/logos/adx_abctrainer.png') }}"></a></div>
            <div class="col-4"></div>
            <div class="col-4"><img height="70px" src="{{ url_for('static',filename='img/logos/adx_vscorona.png') }}"></div>
        </div>
        <div class="row">
            <div class="col">
                <div class="row"><h3>Wunsch-Training</h3></div>
                    <form action="" method="post" novalidate class="form-inline">
                        <div class="form-group">
                            {{ form.word.label(class='sr-only') }}<br>
                            {{ form.word(size=20,class='form-control mb-2 mr-sm-2', placeholder='Zauberwort eingeben...') }}
                            {% if form.pwd %}
                                {{ form.pwd.label(class='sr-only') }}<br>
                                {{ form.pwd(size=12,class='form-control mb-2 mr-sm-2', placeholder='Passwort...') }}
                            {% endif %}
                            {{ form.submit_word(class='btn btn-primary mb-2',val='1') }}
                            {{ form.csrf_token }}
                        </div>
                    </form>
                {% if form.errors and submitted['word'] %}
                      {% for error in form.word.errors %}
                          <div class="alert alert-danger"><strong><i class="fas fa-bomb"></i> {{ error }}</strong></div>
                      {% endfor %}
                        {% if form.pwd %}
                            {% for error in form.pwd.errors %}
                              <div class="alert alert-danger"><strong><i class="fas fa-bomb"></i> {{ error }}</strong></div>
                          {% endfor %}
                        {% endif %}
                {% endif %}
                <div class="alert alert-primary">
                    <small><i class="fas fa-info"></i> Worte sollten zwischen {{ min }} und {{ max }} Buchstaben haben. Sonderzeichen und Umlaute dürfen nicht vorkommen.</small>
                </div>
                {% if form_2 %}
                    <div class="row"><h3>Zufalls-Training</h3></div>
                    <form action="" method="post" class="form-inline">
                            <div class="form-group">
                                {{ form_2.min.label(class='sr-only') }}
                                <div class="adx-input-group mb-2 mr-sm-2">
                                        <span>Zwischen</span>
                                        {{ form_2.min(min=min, max=max, class='adx-form-int form-control', value=min) }}
                                        {{ form_2.max.label(class='sr-only') }}
                                        <span>und</span>
                                        {{ form_2.max(min=min, max=max, class='adx-form-int form-control', value=max) }}
                                        <span>Buchstaben.</span>
                                </div>
                                {{ form_2.submit_random(class='btn btn-primary mb-2',val='2') }}
                                {{ form_2.csrf_token }}
                            </div>
                    </form>
                <div class="alert alert-primary">
                    <small><i class="fas fa-info"></i> Worte werden nach dem sogennanten "Zufallsprinzip" aus einer Liste mit knapp 650 Wörtern ausgewählt. Verwendung auf eigene Gefahr!</small>
                </div>
                {% endif %}
            </div>
            <div class="col">
                <div class="row"><h3>Vom Cheftrainer Empfohlen</h3></div>
                <div class="row">
                    <div class="list-group list-group-horizontal">
                        {% for word in word_list %}
                            <a href="{{url_for('adx_abctrainer.abctrainer_word',word=word.lower())}}" class='adx-recommended list-group-item list-group-item-action'>{{ word.upper() }}</a>
                            {% if loop.index % 4 == 0 %}
                                </div><div class="list-group list-group-horizontal">
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/adx_abctrainer/word.html
{% extends "base.html" %}

{% block title %}
    AUDAX - ABC Trainings Generator
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='abc_trainer.css') }}">
{% endblock %}

{% block content %}
    <div class="container-xl">
        <div class="col adx-wordbox">
            <div class="adx-logo-row row">
                <div class="col-3"><a href="{{ url_for('adx_abctrainer.abctrainer_form') }}"><img src="{{ url_for('static',filename='img/logos/adx_abctrainer.png') }}"></a></div>
                <div class="col-2"></div>
                <div class="col-3"><a target="_blank" href="https://www.audax-sv.de/"><img src="{{ url_for('static',filename='img/logos/adx_vscorona.png') }}"></a></div>
            </div>
                {% for letter_path in word %}
                    <img src="{{ letter_path }}" class="adx-letter">
                {% endfor %}
            <div class="row adx-infobox">
                <div class="alert alert-info" role="alert">
                    <i class="fas fa-exclamation"></i> Alle Übungen so schnell wie möglich abarbeiten. Pausen nur wenn nötig einlegen.<br/>
                    <i class="fas fa-info"></i> Präsentiert von <a target="_blank" href="https://heartbrands.eu/de/">heartbrands.eu</a> und <a target="_blank" href="https://www.audax-sv.de/">audax.hamburg</a>.<br/>
                    <i class="fas fa-info"></i> Gemacht mit <i class="fas fa-heart"></i> und <a href="https://www.python.org/" target="_blank"><i class="fab fa-python"></i></a> von <A HREF="&#109;&#97;&#105;&#108;&#116;&#111;&#58;%66%72%69%64%61%79%6E%69%67%68%74%73%61%72%65%6B%69%6C%6C%69%6E%67%6D%65%2B%61%62%63%74%72%61%69%6E%65%72%40%67%6D%61%69%6C%2E%63%6F%6D">Markus</A>.<br/>
                </div>
            </div>
            <div class="row adx-word-row">
                <a href="{{ url_for('adx_abctrainer.abctrainer_form') }}" class="btn btn-primary adx-button"><strong>Zur Startseite!</strong></a>

    {#                <a href="{{ url_for('adx_abctrainer.abctrainer_random') }}" class="btn btn-primary adx-button">Neue Zufalls-Übung!</a>#}
            </div>
            <div class="row adx-word-row">
                <form action="" method="post" class="form-inline">
                    <div class="form-group">
                        {{ form_2.min.label(class='sr-only') }}
                        <div class="adx-input-group mb-2 mr-sm-2">
                                    <span>Neues Zufallswort mit</span>
                                    {{ form_2.min(min=min_abs, max=max_abs, class='form-control adx-form-int', value=min) }}
                                    {{ form_2.max.label(class='sr-only') }}
                                    <span>bis</span>
                                    {{ form_2.max(min=min_abs, max=max_abs, class='form-control adx-form-int', value=max) }}
                                    <span>Buchstaben.</span>
                            </div>
                        {{ form_2.submit_random(class='btn btn-primary mb-2') }}
                        {{ form_2.csrf_token }}
                    </div>
                </form>
                {% if form_2.errors %}
                    {% for error in form_2.min.errors %}
                        <div class="alert alert-danger"><strong><i class="fas fa-bomb"></i> {{ error }}</strong></div>
                    {% endfor %}
                    {% for error in form_2.max.errors %}
                        <div class="alert alert-danger"><strong><i class="fas fa-bomb"></i> {{ error }}</strong></div>
                    {% endfor %}
                {% endif %}
            </div>
    {#    <div class="row justify-content-center">#}
    {#        <div>#}
    {#        <div class="col-2">#}
    {#            <a href="{{ url_for('adx_abctrainer.abctrainer_form') }}" class="btn btn-primary">Neue Übung!</a>#}
    {#        </div>#}
    {#    </div>#}
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="data:,">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% block custom_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container flash-container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>